server:
  address: 0.0.0.0
  port: {PORT}

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: {SPRING_DATASOURCE_URL}
    username: {SPRING_DATASOURCE_USERNAME}
    password: {SPRING_DATASOURCE_PASSWORD}
    hikari:
      pool-name: main_db_pool
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  liquibase:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd

zk:
  homepage: zul/index
