server:
  address: 0.0.0.0
  port: {PORT}

spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  liquibase:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss

zk:
  homepage: zul/index
